config/routes.rb
Ctn::Application.routes.draw do
  get "main/index"

  resources :articles

 root to: 'main#index', as: 'main'

end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :date, :link, :newsSource, :title, :topic
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @articles }
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = Article.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/new
  # GET /articles/new.json
  def new
    @article = Article.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find(params[:id])
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(params[:article])

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render json: @article, status: :created, location: @article }
      else
        format.html { render action: "new" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /articles/1
  # PUT /articles/1.json
  def update
    @article = Article.find(params[:id])

    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
        @topics = Article.select(:topic)

  end

  def get_urls
    selected_topic = Article.find(params[:article][:topic])
    @urls = Article.where("topic = ?", selected_topic)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    News Source<br />
    <%= f.text_field :newsSource %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
    <div class="field">
      <%= f.label :topic %><br />
      <%= f.text_field :topic %>
    </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.text_field :date %>
  </div>

  <div class="field">
    <%= f.label :link %><br />
    <%= f.text_field :link %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Listing articles</h1>

<table>
  <tr>
    <th>News Source</th>
    <th>Title</th>
    <th>Date</th>
    <th>Topic</th>
    <th>Link</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @articles.each do |article| %>
  <tr>
    <td><%= article.newsSource %></td>
    <td><%= article.title %></td>
    <td><%= article.date %></td>
    <td><%= article.topic %></td>
    <td><%= article.link %></td>
    <td><%= link_to 'Show', article %></td>
    <td><%= link_to 'Edit', edit_article_path(article) %></td>
    <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>News Source:</b>
  <%= @article.newsSource %>
</p>

<p>
  <b>Title:</b>
  <%= @article.title %>
</p>

<p>
  <b>Date:</b>
  <%= @article.date %>
</p>

<p>
  <b>Topic:</b>
  <%= @article.topic %>
</p>

<p>
  <b>Link:</b>
  <%= @article.link %>
</p>


<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Compare The News</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= link_to image_tag("logo.jpg"), main_path %>
  <%= form_tag("/search", :method => "get") do %>
      <%= label_tag(:q, "Search for:") %>
      <%= text_field_tag(:q) %>
      <%= submit_tag("Search") %>
  <% end %>
  <%= link_to 'New Article', new_article_path %>
</head>
<body>

<%= yield %>
</body>
</html>

app/views/main/index.html.erb
<h1></br></h1>
<div class ="container">

<div class= "forms ">
<form name="myform"   method="GET" class ="leftForm">

  <%=collection_select("article", "newsSource", @urls, :id, :newsSource, :prompt => "Select Topic")%>

</form>

  <form name="topics"   method="GET" class ="topicForm">

   <%=collection_select("article", "topic", Article.all, :id, :topic,
   :prompt => "Select Topic", :onchange => remote_function(:url => {:action => 'get_urls'},
   :with => "'id=' + this.value"))%>

  </form>

<form name="myform2" method="GET" class = "rightForm">

    <select name="newsRight" >
      <option>News Source</option>
      <option value="fox">Fox News</option>
      <option value="msnbc">MSNBC</option>
      <option value="cnn">CNN</option>
      <option value="abc">ABC</option>
    </select>

</form>
</div>


<div class="panels">
  <object type="text/html" data="msnbc.com" width ="49.5%" height="100%" ></object>
  <object type="text/html" data="foxnews.com" width ="49.5%"height="100%" ></object>
</div>
</div>